Repository azooKey/azooKey-Desktop, pull requests merged in 2024-10, with the labels that each got.

#79 docs: README.mdを更新
  README.md
Labels: documentation

#78 experimental: ChatGPT APIを利用した予測入力機能のベースを実装
  azooKeyMac.xcodeproj/project.pbxproj
  azooKeyMac/Configs/BoolConfigItem.swift
  azooKeyMac/InputController/Actions/ClientAction.swift
  azooKeyMac/InputController/Actions/UserAction.swift
  azooKeyMac/InputController/CandidateView.swift
  azooKeyMac/InputController/InputMode.swift
  azooKeyMac/InputController/InputState.swift
  azooKeyMac/InputController/OpenAIClient.swift
  azooKeyMac/InputController/SegmentsManager.swift
  azooKeyMac/InputController/SuggestionView.swift
  azooKeyMac/InputController/azooKeyMacInputController.swift
  azooKeyMac/Windows/ConfigWindow.swift
  azooKeyMac/azooKeyMac.entitlements
Labels: enhancement

#75 fix: Zenzaiがなくてもユーザ辞書が動作するように修正
  azooKeyMac.xcodeproj/project.pbxproj
  azooKeyMac/InputController/SegmentsManager.swift
Labels: bug

#82 refactor: use folders instead of groups
  azooKeyMac.xcodeproj/project.pbxproj
Labels: enhancement
